[workspace]
resolver = "2"
members = [
  "dna/integrity_zomes/*",
  "dna/coordinator_zomes/*"
]

[workspace.dependencies]
hdi = "=0.1.10"
hdk = "0.0.163"
serde = "1"


[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
