[workspace]
resolver = "2"
members = [
  "dna/integrity_zomes/*",
  "dna/coordinator_zomes/*"
]

[workspace.dependencies]
hdi = "0.2.0-beta-rc.0"
hdk = "0.1.0-beta-rc.0"
serde = "1"


[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
